image:  node:10.16.0

variables:
  PACKAGE_PATH:  /test

stages:
  - test
  - build
  - deploy

before_script:
  - ls

unit_tests:
  stage: test
  script:
    - ls

build:
  image: docker
  only:
    - master
  stage:  build
  services:
    - docker:18-dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
  script:
    - ls
    # - docker build -t test-image .
    # - docker images
    # push image to dockerhub

deploy:
  only:
    - master
  stage:  deploy
  script:
    # ssh to deploy on server
    - ls
